name: picocrypt
summary: A very small, very simple, yet very secure cryptography utility.
description: Picocrypt is a very small (hence "Pico"), very simple, yet very secure cryptography utility that you can use to encrypt files, generate checksums, shred files, and much more. It's designed to be the go-to tool for encryption, with a focus on security, simplicity, and reliability. Picocrypt uses the secure XChaCha20 cipher and the Poly1305 message authentication code to provide a high level of security, even from three-letter agencies like the NSA. It's designed for maximal security, making absolutely no compromises security-wise, and is built with an audited cryptography library. Your privacy and security are under attack. Take it back with confidence by protecting your files with Picocrypt.
version: '1.13'
confinement: strict
base: core18
grade: stable
compression: xz

apps:
  picocrypt:
    command: bin/Picocrypt
    extensions: [gnome-3-28]
    plugs:
      - opengl

parts:
  picocrypt:
    plugin: go
    go-importpath: .
    source: .
    build-packages:
      - gcc
      - make
      - libx11-dev
      - libxcursor-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxi-dev
      - libgl1-mesa-dev
      - libxxf86vm-dev
      - libgtk-3-dev
    stage-packages:
      - xclip
      - xdg-utils
      - libglu1-mesa
      - language-pack-en-base
      - coreutils
    after:
      - desktop-glib-only
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

plugs:
  picocrypt-home:
    interface: home
  picocrypt-network:
    interface: network
