name: picocrypt
summary: A very small, very simple, yet very secure encryption tool.
version: "1.23"
confinement: strict
base: core20
grade: stable
compression: xz

apps:
  picocrypt:
    command: bin/Picocrypt
    extensions: [gnome-3-38]
    plugs:
      - opengl

parts:
  picocrypt:
    plugin: go
    source: .
    build-packages:
      - gcc
      - xorg-dev
      - libgtk-3-dev
    stage-packages:
      - libglu1-mesa
      - xclip
    after:
      - desktop-glib-only
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

plugs:
  picocrypt-home:
    interface: home
  picocrypt-network:
    interface: network
